package com.devin.data.analysis.admin.product.integration;

import com.devin.data.analysis.admin.product.dto.DaEveryColorData;
import com.devin.data.analysis.admin.product.dto.example.DaEveryColorDataExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DaEveryColorDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    long countByExample(DaEveryColorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    int deleteByExample(DaEveryColorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String idEveryColorData);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    int insert(DaEveryColorData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") DaEveryColorData record, @Param("selective") DaEveryColorData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaEveryColorData selectOneByExample(DaEveryColorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaEveryColorData selectOneByExampleSelective(@Param("example") DaEveryColorDataExample example, @Param("selective") DaEveryColorData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DaEveryColorData> selectByExampleSelective(@Param("example") DaEveryColorDataExample example, @Param("selective") DaEveryColorData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    List<DaEveryColorData> selectByExample(DaEveryColorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaEveryColorData selectByPrimaryKeySelective(@Param("idEveryColorData") String idEveryColorData, @Param("selective") DaEveryColorData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    DaEveryColorData selectByPrimaryKey(String idEveryColorData);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") DaEveryColorData record, @Param("example") DaEveryColorDataExample example, @Param("selective") DaEveryColorData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaEveryColorData record, @Param("example") DaEveryColorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") DaEveryColorData record, @Param("selective") DaEveryColorData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaEveryColorData record);
}