package com.devin.data.analysis.admin.product.integration;

import com.devin.data.analysis.admin.product.dto.DaProduct;
import com.devin.data.analysis.admin.product.dto.example.DaProductExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DaProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    long countByExample(DaProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    int deleteByExample(DaProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String idDaProduct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    int insert(DaProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") DaProduct record, @Param("selective") DaProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaProduct selectOneByExample(DaProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaProduct selectOneByExampleSelective(@Param("example") DaProductExample example, @Param("selective") DaProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaProduct selectOneByExampleWithBLOBs(DaProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DaProduct> selectByExampleSelective(@Param("example") DaProductExample example, @Param("selective") DaProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    List<DaProduct> selectByExampleWithBLOBs(DaProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    List<DaProduct> selectByExample(DaProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaProduct selectByPrimaryKeySelective(@Param("idDaProduct") String idDaProduct, @Param("selective") DaProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    DaProduct selectByPrimaryKey(String idDaProduct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") DaProduct record, @Param("example") DaProductExample example, @Param("selective") DaProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DaProduct record, @Param("example") DaProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaProduct record, @Param("example") DaProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") DaProduct record, @Param("selective") DaProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DaProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaProduct record);
}