package com.devin.data.analysis.admin.product.dto;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class DaEveryColorData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.id_every_color_data
     *
     * @mbg.generated
     */
    private String idEveryColorData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.product_code
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.lottery_period
     *
     * @mbg.generated
     */
    private String lotteryPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.lottery_date
     *
     * @mbg.generated
     */
    private LocalDateTime lotteryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.wan_digit
     *
     * @mbg.generated
     */
    private Byte wanDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.qian_digit
     *
     * @mbg.generated
     */
    private Byte qianDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.bai_digit
     *
     * @mbg.generated
     */
    private Byte baiDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.shi_digit
     *
     * @mbg.generated
     */
    private Byte shiDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.ge_digit
     *
     * @mbg.generated
     */
    private Byte geDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.big_deal
     *
     * @mbg.generated
     */
    private String bigDeal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.vingt_etun
     *
     * @mbg.generated
     */
    private String vingtEtun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_every_color_data.parity
     *
     * @mbg.generated
     */
    private String parity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.id_every_color_data
     *
     * @return the value of da_every_color_data.id_every_color_data
     *
     * @mbg.generated
     */
    public String getIdEveryColorData() {
        return idEveryColorData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.id_every_color_data
     *
     * @param idEveryColorData the value for da_every_color_data.id_every_color_data
     *
     * @mbg.generated
     */
    public void setIdEveryColorData(String idEveryColorData) {
        this.idEveryColorData = idEveryColorData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.product_code
     *
     * @return the value of da_every_color_data.product_code
     *
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.product_code
     *
     * @param productCode the value for da_every_color_data.product_code
     *
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.lottery_period
     *
     * @return the value of da_every_color_data.lottery_period
     *
     * @mbg.generated
     */
    public String getLotteryPeriod() {
        return lotteryPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.lottery_period
     *
     * @param lotteryPeriod the value for da_every_color_data.lottery_period
     *
     * @mbg.generated
     */
    public void setLotteryPeriod(String lotteryPeriod) {
        this.lotteryPeriod = lotteryPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.lottery_date
     *
     * @return the value of da_every_color_data.lottery_date
     *
     * @mbg.generated
     */
    public LocalDateTime getLotteryDate() {
        return lotteryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.lottery_date
     *
     * @param lotteryDate the value for da_every_color_data.lottery_date
     *
     * @mbg.generated
     */
    public void setLotteryDate(LocalDateTime lotteryDate) {
        this.lotteryDate = lotteryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.wan_digit
     *
     * @return the value of da_every_color_data.wan_digit
     *
     * @mbg.generated
     */
    public Byte getWanDigit() {
        return wanDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.wan_digit
     *
     * @param wanDigit the value for da_every_color_data.wan_digit
     *
     * @mbg.generated
     */
    public void setWanDigit(Byte wanDigit) {
        this.wanDigit = wanDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.qian_digit
     *
     * @return the value of da_every_color_data.qian_digit
     *
     * @mbg.generated
     */
    public Byte getQianDigit() {
        return qianDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.qian_digit
     *
     * @param qianDigit the value for da_every_color_data.qian_digit
     *
     * @mbg.generated
     */
    public void setQianDigit(Byte qianDigit) {
        this.qianDigit = qianDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.bai_digit
     *
     * @return the value of da_every_color_data.bai_digit
     *
     * @mbg.generated
     */
    public Byte getBaiDigit() {
        return baiDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.bai_digit
     *
     * @param baiDigit the value for da_every_color_data.bai_digit
     *
     * @mbg.generated
     */
    public void setBaiDigit(Byte baiDigit) {
        this.baiDigit = baiDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.shi_digit
     *
     * @return the value of da_every_color_data.shi_digit
     *
     * @mbg.generated
     */
    public Byte getShiDigit() {
        return shiDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.shi_digit
     *
     * @param shiDigit the value for da_every_color_data.shi_digit
     *
     * @mbg.generated
     */
    public void setShiDigit(Byte shiDigit) {
        this.shiDigit = shiDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.ge_digit
     *
     * @return the value of da_every_color_data.ge_digit
     *
     * @mbg.generated
     */
    public Byte getGeDigit() {
        return geDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.ge_digit
     *
     * @param geDigit the value for da_every_color_data.ge_digit
     *
     * @mbg.generated
     */
    public void setGeDigit(Byte geDigit) {
        this.geDigit = geDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.big_deal
     *
     * @return the value of da_every_color_data.big_deal
     *
     * @mbg.generated
     */
    public String getBigDeal() {
        return bigDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.big_deal
     *
     * @param bigDeal the value for da_every_color_data.big_deal
     *
     * @mbg.generated
     */
    public void setBigDeal(String bigDeal) {
        this.bigDeal = bigDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.vingt_etun
     *
     * @return the value of da_every_color_data.vingt_etun
     *
     * @mbg.generated
     */
    public String getVingtEtun() {
        return vingtEtun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.vingt_etun
     *
     * @param vingtEtun the value for da_every_color_data.vingt_etun
     *
     * @mbg.generated
     */
    public void setVingtEtun(String vingtEtun) {
        this.vingtEtun = vingtEtun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_every_color_data.parity
     *
     * @return the value of da_every_color_data.parity
     *
     * @mbg.generated
     */
    public String getParity() {
        return parity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_every_color_data.parity
     *
     * @param parity the value for da_every_color_data.parity
     *
     * @mbg.generated
     */
    public void setParity(String parity) {
        this.parity = parity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idEveryColorData=").append(idEveryColorData);
        sb.append(", productCode=").append(productCode);
        sb.append(", lotteryPeriod=").append(lotteryPeriod);
        sb.append(", lotteryDate=").append(lotteryDate);
        sb.append(", wanDigit=").append(wanDigit);
        sb.append(", qianDigit=").append(qianDigit);
        sb.append(", baiDigit=").append(baiDigit);
        sb.append(", shiDigit=").append(shiDigit);
        sb.append(", geDigit=").append(geDigit);
        sb.append(", bigDeal=").append(bigDeal);
        sb.append(", vingtEtun=").append(vingtEtun);
        sb.append(", parity=").append(parity);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DaEveryColorData other = (DaEveryColorData) that;
        return (this.getIdEveryColorData() == null ? other.getIdEveryColorData() == null : this.getIdEveryColorData().equals(other.getIdEveryColorData()))
            && (this.getProductCode() == null ? other.getProductCode() == null : this.getProductCode().equals(other.getProductCode()))
            && (this.getLotteryPeriod() == null ? other.getLotteryPeriod() == null : this.getLotteryPeriod().equals(other.getLotteryPeriod()))
            && (this.getLotteryDate() == null ? other.getLotteryDate() == null : this.getLotteryDate().equals(other.getLotteryDate()))
            && (this.getWanDigit() == null ? other.getWanDigit() == null : this.getWanDigit().equals(other.getWanDigit()))
            && (this.getQianDigit() == null ? other.getQianDigit() == null : this.getQianDigit().equals(other.getQianDigit()))
            && (this.getBaiDigit() == null ? other.getBaiDigit() == null : this.getBaiDigit().equals(other.getBaiDigit()))
            && (this.getShiDigit() == null ? other.getShiDigit() == null : this.getShiDigit().equals(other.getShiDigit()))
            && (this.getGeDigit() == null ? other.getGeDigit() == null : this.getGeDigit().equals(other.getGeDigit()))
            && (this.getBigDeal() == null ? other.getBigDeal() == null : this.getBigDeal().equals(other.getBigDeal()))
            && (this.getVingtEtun() == null ? other.getVingtEtun() == null : this.getVingtEtun().equals(other.getVingtEtun()))
            && (this.getParity() == null ? other.getParity() == null : this.getParity().equals(other.getParity()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdEveryColorData() == null) ? 0 : getIdEveryColorData().hashCode());
        result = prime * result + ((getProductCode() == null) ? 0 : getProductCode().hashCode());
        result = prime * result + ((getLotteryPeriod() == null) ? 0 : getLotteryPeriod().hashCode());
        result = prime * result + ((getLotteryDate() == null) ? 0 : getLotteryDate().hashCode());
        result = prime * result + ((getWanDigit() == null) ? 0 : getWanDigit().hashCode());
        result = prime * result + ((getQianDigit() == null) ? 0 : getQianDigit().hashCode());
        result = prime * result + ((getBaiDigit() == null) ? 0 : getBaiDigit().hashCode());
        result = prime * result + ((getShiDigit() == null) ? 0 : getShiDigit().hashCode());
        result = prime * result + ((getGeDigit() == null) ? 0 : getGeDigit().hashCode());
        result = prime * result + ((getBigDeal() == null) ? 0 : getBigDeal().hashCode());
        result = prime * result + ((getVingtEtun() == null) ? 0 : getVingtEtun().hashCode());
        result = prime * result + ((getParity() == null) ? 0 : getParity().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table da_every_color_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        idEveryColorData("id_every_color_data", "idEveryColorData", "CHAR", false),
        productCode("product_code", "productCode", "CHAR", false),
        lotteryPeriod("lottery_period", "lotteryPeriod", "VARCHAR", false),
        lotteryDate("lottery_date", "lotteryDate", "TIMESTAMP", false),
        wanDigit("wan_digit", "wanDigit", "TINYINT", false),
        qianDigit("qian_digit", "qianDigit", "TINYINT", false),
        baiDigit("bai_digit", "baiDigit", "TINYINT", false),
        shiDigit("shi_digit", "shiDigit", "TINYINT", false),
        geDigit("ge_digit", "geDigit", "TINYINT", false),
        bigDeal("big_deal", "bigDeal", "CHAR", false),
        vingtEtun("vingt_etun", "vingtEtun", "CHAR", false),
        parity("parity", "parity", "CHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_every_color_data
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}