package com.devin.data.analysis.admin.product.dto;

import java.util.ArrayList;
import java.util.Arrays;

public class DaProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_product.id_da_product
     *
     * @mbg.generated
     */
    private String idDaProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_product.product_code
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_product.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_product.product_abbr
     *
     * @mbg.generated
     */
    private String productAbbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_product.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_product.product_channel
     *
     * @mbg.generated
     */
    private String productChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_product.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column da_product.product_des
     *
     * @mbg.generated
     */
    private String productDes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_product.id_da_product
     *
     * @return the value of da_product.id_da_product
     *
     * @mbg.generated
     */
    public String getIdDaProduct() {
        return idDaProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_product.id_da_product
     *
     * @param idDaProduct the value for da_product.id_da_product
     *
     * @mbg.generated
     */
    public void setIdDaProduct(String idDaProduct) {
        this.idDaProduct = idDaProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_product.product_code
     *
     * @return the value of da_product.product_code
     *
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_product.product_code
     *
     * @param productCode the value for da_product.product_code
     *
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_product.product_name
     *
     * @return the value of da_product.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_product.product_name
     *
     * @param productName the value for da_product.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_product.product_abbr
     *
     * @return the value of da_product.product_abbr
     *
     * @mbg.generated
     */
    public String getProductAbbr() {
        return productAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_product.product_abbr
     *
     * @param productAbbr the value for da_product.product_abbr
     *
     * @mbg.generated
     */
    public void setProductAbbr(String productAbbr) {
        this.productAbbr = productAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_product.product_type
     *
     * @return the value of da_product.product_type
     *
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_product.product_type
     *
     * @param productType the value for da_product.product_type
     *
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_product.product_channel
     *
     * @return the value of da_product.product_channel
     *
     * @mbg.generated
     */
    public String getProductChannel() {
        return productChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_product.product_channel
     *
     * @param productChannel the value for da_product.product_channel
     *
     * @mbg.generated
     */
    public void setProductChannel(String productChannel) {
        this.productChannel = productChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_product.status
     *
     * @return the value of da_product.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_product.status
     *
     * @param status the value for da_product.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_product.product_des
     *
     * @return the value of da_product.product_des
     *
     * @mbg.generated
     */
    public String getProductDes() {
        return productDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_product.product_des
     *
     * @param productDes the value for da_product.product_des
     *
     * @mbg.generated
     */
    public void setProductDes(String productDes) {
        this.productDes = productDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idDaProduct=").append(idDaProduct);
        sb.append(", productCode=").append(productCode);
        sb.append(", productName=").append(productName);
        sb.append(", productAbbr=").append(productAbbr);
        sb.append(", productType=").append(productType);
        sb.append(", productChannel=").append(productChannel);
        sb.append(", status=").append(status);
        sb.append(", productDes=").append(productDes);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DaProduct other = (DaProduct) that;
        return (this.getIdDaProduct() == null ? other.getIdDaProduct() == null : this.getIdDaProduct().equals(other.getIdDaProduct()))
            && (this.getProductCode() == null ? other.getProductCode() == null : this.getProductCode().equals(other.getProductCode()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getProductAbbr() == null ? other.getProductAbbr() == null : this.getProductAbbr().equals(other.getProductAbbr()))
            && (this.getProductType() == null ? other.getProductType() == null : this.getProductType().equals(other.getProductType()))
            && (this.getProductChannel() == null ? other.getProductChannel() == null : this.getProductChannel().equals(other.getProductChannel()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getProductDes() == null ? other.getProductDes() == null : this.getProductDes().equals(other.getProductDes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdDaProduct() == null) ? 0 : getIdDaProduct().hashCode());
        result = prime * result + ((getProductCode() == null) ? 0 : getProductCode().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getProductAbbr() == null) ? 0 : getProductAbbr().hashCode());
        result = prime * result + ((getProductType() == null) ? 0 : getProductType().hashCode());
        result = prime * result + ((getProductChannel() == null) ? 0 : getProductChannel().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getProductDes() == null) ? 0 : getProductDes().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table da_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        idDaProduct("id_da_product", "idDaProduct", "CHAR", false),
        productCode("product_code", "productCode", "CHAR", false),
        productName("product_name", "productName", "VARCHAR", false),
        productAbbr("product_abbr", "productAbbr", "VARCHAR", false),
        productType("product_type", "productType", "CHAR", false),
        productChannel("product_channel", "productChannel", "VARCHAR", false),
        status("status", "status", "CHAR", true),
        productDes("product_des", "productDes", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table da_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}