package com.devin.data.analysis.admin.login.integration;

import com.devin.data.analysis.admin.login.dto.DaAdmin;
import com.devin.data.analysis.admin.login.dto.example.DaAdminExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DaAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     */
    long countByExample(DaAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     */
    int deleteByExample(DaAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String idDaAdmin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     */
    int insert(DaAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") DaAdmin record, @Param("selective") DaAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaAdmin selectOneByExample(DaAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaAdmin selectOneByExampleSelective(@Param("example") DaAdminExample example, @Param("selective") DaAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DaAdmin> selectByExampleSelective(@Param("example") DaAdminExample example, @Param("selective") DaAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     */
    List<DaAdmin> selectByExample(DaAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaAdmin selectByPrimaryKeySelective(@Param("idDaAdmin") String idDaAdmin, @Param("selective") DaAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     */
    DaAdmin selectByPrimaryKey(String idDaAdmin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") DaAdmin record, @Param("example") DaAdminExample example, @Param("selective") DaAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaAdmin record, @Param("example") DaAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") DaAdmin record, @Param("selective") DaAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table da_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaAdmin record);
}